#build

FROM gradle:9.1-jdk25 AS builder
WORKDIR /app
COPY . .

# Set RUN_TESTS=true to execute tests during build (used by `make test`)
ARG RUN_TESTS=false

RUN chmod +x ./gradlew && \
    if [ "$RUN_TESTS" = "true" ]; then \
        ./gradlew :app:test \
            --tests "*MiniExchangeApplicationTests" \
            --stacktrace \
            --scan \
            --info \
            --no-daemon \
	    :app:bootJar; \
    else \
        ./gradlew :app:bootJar --no-daemon; \
    fi


#run
FROM eclipse-temurin:25-jre
WORKDIR /app
COPY --from=builder /app/app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
