#build

FROM gradle:9.1-jdk25 AS builder
WORKDIR /app
COPY . .
RUN chmod +x ./gradlew && ./gradlew :app:bootJar --no-daemon


#run
FROM eclipse-temurin:25-jre
WORKDIR /app
COPY --from=builder /app/app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]